insert into Genres (type) values ('фэнтези')
insert into Authors (name, surname) values ('Джоан', 'Роулинг')
insert into Books(title, author_id, genre_id) values ('Гарри Поттер и Философский камень', 1, 1)
insert into Comments(text, book_id) values ('Классная книга!', 1)
insert into Comments(text, book_id) values ('И мне понравилась', 1)
insert into Comments(text, book_id) values ('Моя любимая', 1)
insert into Comments(text, book_id) values ('А мне больше орден феникса нравится', 1)
insert into Books(title, author_id, genre_id) values ('Гарри Поттер и Узник Азкабана', 1, 1)
insert into Genres (type) values ('детектив')
insert into Authors (name, surname) values ('Артур', 'Конан Дойль')
insert into Books(title, author_id, genre_id) values ('Шерлок Холмс', 2, 2)
insert into Genres (type) values ('ужасы')
insert into Authors (name, surname) values ('Стивен', 'Кинг')
insert into Books(title, author_id, genre_id) values ('Темная Башня', 3, 3)


