server:
  port: 3091

management:
  server:
    port: 3090

  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics, loggers, hystrix-stream, threaddump,configprops

rest:
  host: localhost
  port1: 4090
  port2: 2090
  scheme: http
  userInfoServicePath: /user
  subsServicePath: /subscription
  subsServiceAdminPath: /subscriptions
  subsUserServicePath: /user/

  readTimeout: 5
  connectTimeout: 4

service:
  locale: ru_RU

spring:
  application:
    name: client-service

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{70}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

  level:
    root: info

    org:
      hibernate: info
      springframework: info

    com:
      netflix:
        eureka: OFF
        discovery: OFF

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
#  file:
#    name: logs/mylog.log