server:
  port: 4011

service:
  locale: ru_RU


type-properties:
  maxChange: 5
  maxCost: 450
  minCost: 200
  change:
    name: event_1
    message: Цена акции компании
    middle: выросла на

  max:
    name: event_2
    message: Максимальная цена акции компании
    middle: достигла
  min:
    name: event_3
    message: Минимальная цена акции компании
    middle: упала ниже

  cacheLifeTime: 24

spring:
  application:
    name: handle-service-stock
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092


      bindings:
        update-cache-in:
          destination: update-cache-info
          contentType: application/json
        subscribing-filter-in:
          destination: subscribing-filter
          contentType: application/json
        stock-info-out:
          destination: stock-info
          contentType: application/json
        error-out:
          destination: error
          contentType: application/json


logging:
  pattern: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{70}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

  level:
    root: info
    com:
      netflix:
        eureka: OFF
        discovery: OFF
    org:
      springframework: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



#  file:
#    name: logs/mylog.log