service:
  locale: ru_RU

spring:
#  application:
#    name: book-service
  data:
    mongodb:
      authentication-database: admin
      database: BookService
      host: localhost
      port: 27017

  mongock:
    change-logs-scan-package:
      - ru.otus.spring.changelogs
    runner-type: initializingbean

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{70}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

  level:
    root: info

    org:
      springframework:
        data: DEBUG
#          mongodb:
#            core:
#              MongoTemplate: DEBUG


#  file:
#    name: logs/mylog.log